name : "deploying to production"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: initialize npm
          run: npm init -y
    
        - name: Install dependencies
          run: npm ci

        - name: Run tests
          run: npm test

        - name: convert it into a zip file
          run : |
            mkdir output
            cp -r src output/
            cp package.json output
            zip -r build.zip output

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: build-zip
            path: build.zip
           
          
        - name: Notify Success via Email
          if: success()
          uses: dawidd6/action-send-mail@v3
          with:
           server_address: smtp.gmail.com
           server_port: 587
           username: nikhil89041@gmail.com
           password: mbop rmsk vqav cbnh
           subject: "✅ CI Build Success - ${{ github.repository }}"
           body: |
            The build for ${{ github.repository }} on branch ${{ github.ref_name }} succeeded.
            Commit: ${{ github.sha }}
           to: awsmine12345@gmail.com
           from: nikhil89041@gmail.com

        
         